on: push
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: go test ./...

  # We build a shared docker image called "zoekt". This is not pushed, but is
  # used for creating the indexserver and webserver images.
  docker:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v2

    # This is the same tag we used for zoekt in the infrastructure repo.
    - name: version
      id: version
      run: .github/workflows/docker-version.sh

    - name: build-zoekt
      uses: docker/build-push-action@v1
      with:
        repository: zoekt
        tags: "latest"
        add_git_labels: "true"
        push: "false"
        build_args: VERSION=${{ steps.version.outputs.value }}

    - name: build-push-webserver
      uses: docker/build-push-action@v1
      with:
        repository: sourcegraph/zoekt-webserver
        tags: ${{ steps.version.outputs.value }},latest
        dockerfile: Dockerfile.webserver
        add_git_labels: "true"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build-push-indexserver
      uses: docker/build-push-action@v1
      with:
        repository: sourcegraph/zoekt-indexserver
        tags: ${{ steps.version.outputs.value }},latest
        dockerfile: Dockerfile.indexserver
        add_git_labels: "true"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  tags:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        if: contains(github.ref, 'test-tags')
        env:
          tags_test_1: "foo"
        run: echo "setting foo"
      - name: bar
        env:
          tags_test_2: "bar"
        run: echo "setting bar"
      - name: all
        env:
          final: ${{ env.tags_*** }}
        run: echo "concat"
  read-tags:
    runs-on: ubuntu-latest
    steps:
      - name: read-env
        run: echo $foo", "$bar", "$final



